//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int IdLibros { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> AñoPublicacion { get; set; }
        public Nullable<int> IdAutor { get; set; }
        public Nullable<int> IdEditorial { get; set; }
        public Nullable<System.DateTime> FechaDePublicacion { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Editorial Editorial { get; set; }
    }
}
