//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibreriaEntities : DbContext
    {
        public LibreriaEntities()
            : base("name=LibreriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<Editorial> Editorials { get; set; }
        public virtual DbSet<Libro> Libros { get; set; }
    
        public virtual ObjectResult<Libro_Result> Libro(string nombreTitulo)
        {
            var nombreTituloParameter = nombreTitulo != null ?
                new ObjectParameter("NombreTitulo", nombreTitulo) :
                new ObjectParameter("NombreTitulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Libro_Result>("Libro", nombreTituloParameter);
        }
    
        public virtual int LibroAdd(string nombre, Nullable<int> añoPublicacion, Nullable<System.DateTime> fechaDePublicacion, Nullable<int> idAutor, Nullable<int> idEditorial)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var añoPublicacionParameter = añoPublicacion.HasValue ?
                new ObjectParameter("AñoPublicacion", añoPublicacion) :
                new ObjectParameter("AñoPublicacion", typeof(int));
    
            var fechaDePublicacionParameter = fechaDePublicacion.HasValue ?
                new ObjectParameter("FechaDePublicacion", fechaDePublicacion) :
                new ObjectParameter("FechaDePublicacion", typeof(System.DateTime));
    
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LibroAdd", nombreParameter, añoPublicacionParameter, fechaDePublicacionParameter, idAutorParameter, idEditorialParameter);
        }
    
        public virtual ObjectResult<LibroGetAll_Result> LibroGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroGetAll_Result>("LibroGetAll");
        }
    
        public virtual ObjectResult<LibroGetByAutor_Result> LibroGetByAutor(Nullable<int> idAutor)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroGetByAutor_Result>("LibroGetByAutor", idAutorParameter);
        }
    
        public virtual ObjectResult<LibroGetByTitulo_Result> LibroGetByTitulo(string titulo)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroGetByTitulo_Result>("LibroGetByTitulo", tituloParameter);
        }
    
        public virtual ObjectResult<LibroGetByEditorial_Result> LibroGetByEditorial(Nullable<int> idEditorial)
        {
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroGetByEditorial_Result>("LibroGetByEditorial", idEditorialParameter);
        }
    
        public virtual ObjectResult<LibroGetByAutorAndFecha_Result> LibroGetByAutorAndFecha(Nullable<int> idAutor, Nullable<System.DateTime> fechaDePublicacion)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            var fechaDePublicacionParameter = fechaDePublicacion.HasValue ?
                new ObjectParameter("FechaDePublicacion", fechaDePublicacion) :
                new ObjectParameter("FechaDePublicacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroGetByAutorAndFecha_Result>("LibroGetByAutorAndFecha", idAutorParameter, fechaDePublicacionParameter);
        }
    
        public virtual int LibroDeleteAutor(Nullable<int> idAutor)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LibroDeleteAutor", idAutorParameter);
        }
    
        public virtual int LibroDeleteEditorial(Nullable<int> idEditorial)
        {
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LibroDeleteEditorial", idEditorialParameter);
        }
    }
}
